# bitbucket-pipelines.yml
image: iterativeai/cml:0-dvc2-base1
runs-on: self.hosted

pipelines:
  custom:
    manual-run:
      - step:
          name: Run training
          script:
            - ./tpi-run.sh
